# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Информация для студентов Академических групп Баскетбольного отделения
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  \"Блог\" о баскетболе.


baseurl: "/basket" # the subpath of your site, e.g. /blog
# url: "http://webjeda.com" # the base hostname & protocol for your site

#sidebar
default-image: basket_logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: ashedko
copyright:
   name: ashedko
   link: 'http://ashedko.github.io'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
# analytics: UA-83979019-1

# Comments
# disqus-shortname: webjeda-demo

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins : [jekyll-paginate, jekyll-seo-tag]


theme: jekyll-theme-leap-day
